import React, { useState, useEffect } from 'react';
import axios from 'axios';

const NotificationCenter = ({ roleContext, userIdContext }) => {
    const [notifications, setNotifications] = useState([]);
    const [loading, setLoading] = useState(false);

    const fetchNotifications = async () => {
        if (!userIdContext) return;
        setLoading(true);
        try {
            // const res = await axios.get(`/api/services/notifications/${userIdContext}`);
            const res = await axios.get(`http://localhost:5000/api/services/notifications/${userIdContext}`);
            setNotifications(res.data);
        } catch (err) {
            console.error("Failed to read notification stream.", err);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchNotifications();
        const syncInterval = setInterval(fetchNotifications, 10000);
        return () => clearInterval(syncInterval);
    }, [userIdContext]);

    const handleMarkAsRead = async (id) => {
        try {
            // await axios.put(`/api/services/notifications/read/${id}`);
            await axios.put(`http://localhost:5000/api/services/notifications/read/${id}`);
            // Optimistically update read state locally for immediate UX feedback
            setNotifications(notifications.map(n => n._id === id ? { ...n, isRead: true } : n));
        } catch (err) {
            console.error("Failed to alter read state reference node.", err);
        }
    };

    const handleClearAll = async () => {
        if (!window.confirm("Are you sure you want to purge all notification payloads from tracking dashboards?")) return;
        try {
            // await axios.delete(`/api/services/notifications/clear/${userIdContext}`);
            await axios.delete(`http://localhost:5000/api/services/notifications/clear/${userIdContext}`);
            setNotifications([]);
        } catch (err) {
            console.error("Failed to clear down notification array indexes.", err);
        }
    };

    return (
        <div className="card border-0 p-4 shadow-sm bg-white rounded-3 animate-fade-in-view">
            <div className="d-flex align-items-center justify-content-between mb-4">
                <div>
                    <h5 className="fw-bold font-monospace text-dark m-0">LIVE LOGGED WORKFLOW ALERT FEED</h5>
                    <p className="text-secondary small m-0">Manage transactional status notes generated by administrators</p>
                </div>
                {notifications.length > 0 && (
                    <button onClick={handleClearAll} className="btn btn-sm btn-outline-danger font-monospace fw-bold px-3">
                        🗑️ PURGE ALL RECORD NODES
                    </button>
                )}
            </div>

            {loading && notifications.length === 0 ? (
                <div className="text-center py-5">
                    <span className="spinner-border spinner-border-sm text-primary"></span>
                    <span className="small font-monospace text-secondary ms-2">LOADING PAYLOAD FILES...</span>
                </div>
            ) : notifications.length === 0 ? (
                <div className="text-center py-5 border border-dashed rounded-3 bg-light">
                    <span className="fs-1 d-block mb-2">📬</span>
                    <p className="text-secondary font-monospace small m-0 fw-bold">No operational log alerts mapped to this profile array context.</p>
                </div>
            ) : (
                <div className="d-flex flex-column gap-3">
                    {notifications.map((alert) => (
                        <div 
                            key={alert._id} 
                            className={`p-3 rounded-3 border transition-all d-flex align-items-start justify-content-between gap-3 ${
                                alert.isRead ? 'bg-light border-light opacity-75' : 'bg-white border-start border-4 border-start-primary shadow-sm'
                            }`}
                        >
                            <div className="flex-grow-1">
                                <div className="d-flex align-items-center gap-2 mb-1">
                                    <span className={`badge font-monospace ${alert.isRead ? 'bg-secondary' : 'bg-primary'}`}>
                                        {alert.title.toUpperCase()}
                                    </span>
                                    <small className="text-muted font-monospace" style={{ fontSize: '0.75rem' }}>
                                        {new Date(alert.createdAt).toLocaleString()}
                                    </small>
                                </div>
                                <p className="m-0 text-dark small fw-medium">{alert.message}</p>
                            </div>
                            {!alert.isRead && (
                                <button 
                                    onClick={() => handleMarkAsRead(alert._id)} 
                                    className="btn btn-sm btn-light border font-monospace tiny-badge px-2 py-1 align-self-center text-nowrap fw-bold"
                                    title="Acknowledge stream state flag change"
                                >
                                    ✓ MARK READ
                                </button>
                            )}
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
};

export default NotificationCenter;